on:
  push:
    branches:
      - main
jobs:
  deploy:
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      name: production
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
      # Construct GitHub Pages URL
      - name: Set GitHub Pages URL
        run: echo "URL=https://<your_github_username>.github.io/<your_repository_name>/" >> $GITHUB_ENV

      # Print the URL for debugging
      - name: Print GitHub Pages URL
        run: echo $URL